[package]
name = "gamelog"
version = "0.3.0"
edition = "2024"

[dependencies]
ron = "0.9"

[dependencies.strum]
version = "0.27"
features = ["derive"]

[dependencies.semver]
version = "1.0"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
